# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixerrapp', '0004_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.CharField(default='{{ gig.user.username}}', max_length=100),
            preserve_default=False,
        ),
    ]
